workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable  # Flutter SDK'nın stabil sürümü
      xcode: latest    # Xcode'un en güncel sürümünü kullanır
    scripts:
      - before_build:
          - echo "Updating Podfile for iOS 13"
          - sed -i "s/platform :ios, '12.0'/platform :ios, '13.0'/g" ios/Podfile
      - name: Temizlik ve Bağımlılıkları Yükleme
        script: |
          flutter clean
          flutter pub get
          sudo gem install cocoapods
          pod repo update
      - name: iOS Build ve Pod Install
        script: |
          flutter build ios --release
          cd ios && pod install --repo-update
      - name: Build IPA ve Artifacts
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa           # iOS IPA dosyasını alır
      - build/ios/iphoneos/*.app      # iOS uygulama dosyasını alır
