workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable  # Flutter SDK'nın stabil sürümü
      xcode: latest    # Xcode'un en güncel sürümünü kullanır
    scripts:
      - name: Temizlik ve Bağımlılıkları Yükleme
        script: |
          flutter clean
          flutter pub get
      - name: iOS Build ve Pod Install
        script: |
          flutter build ios --release    # iOS için release build yapılır
          cd ios && pod install          # Pod bağımlılıklarını yükler
      - name: Build IPA ve Artifacts
        script: |
          flutter build ios --release   # Tekrar build yapılır (gereklidir)
    artifacts:
      - build/ios/ipa/*.ipa           # iOS IPA dosyasını alır
      - build/ios/iphoneos/*.app      # iOS uygulama dosyasını alır
