// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Y-H1O2KZQt-AJbwTYlbi-OU0FdMt3cI',
    appId: '1:616618790162:web:8327bbad7c843049eb77cb',
    messagingSenderId: '616618790162',
    projectId: 'apartman-2a033',
    authDomain: 'apartman-2a033.firebaseapp.com',
    storageBucket: 'apartman-2a033.firebasestorage.app',
    measurementId: 'G-NM80E95V9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7po5qrOq3Xa2-Kam0--q6oNv0eEMEUkY',
    appId: '1:616618790162:android:7c80b56f0ad4ef8beb77cb',
    messagingSenderId: '616618790162',
    projectId: 'apartman-2a033',
    storageBucket: 'apartman-2a033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZGaXQKTWR-TfHhS10kDzsvnXj_Ayl8Ms',
    appId: '1:616618790162:ios:9168431a42929709eb77cb',
    messagingSenderId: '616618790162',
    projectId: 'apartman-2a033',
    storageBucket: 'apartman-2a033.firebasestorage.app',
    iosBundleId: 'com.example.apartman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZGaXQKTWR-TfHhS10kDzsvnXj_Ayl8Ms',
    appId: '1:616618790162:ios:9168431a42929709eb77cb',
    messagingSenderId: '616618790162',
    projectId: 'apartman-2a033',
    storageBucket: 'apartman-2a033.firebasestorage.app',
    iosBundleId: 'com.example.apartman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Y-H1O2KZQt-AJbwTYlbi-OU0FdMt3cI',
    appId: '1:616618790162:web:0c7456c3a0ec30a8eb77cb',
    messagingSenderId: '616618790162',
    projectId: 'apartman-2a033',
    authDomain: 'apartman-2a033.firebaseapp.com',
    storageBucket: 'apartman-2a033.firebasestorage.app',
    measurementId: 'G-FH8X1QEME2',
  );

}